### ISSUE TITLE
Add fourQueen problem in cpp

### ISSUE THREAD

**Issue by MartinaJohn** [1dharode/Hacktoberfest2022#571]

**Comment by MartinaJohn** [comment]
please assign me this issue @CostGranda

**Comment by MartinaJohn** [comment]
pls assign me this issue @1dharode

**Comment by Aditi192002** [comment]
Please assign this issue to me

**Comment by Sandyy07** [comment]
Hi @1dharode , Kindly please assign me this issue.

**Comment by Sakshi2002-Sinha** [comment]
Hello, Please assign this issue to me.
