### ISSUE TITLE
Add No of Islands In Matrix

### ISSUE THREAD

**Issue by shivamxsurya** [1dharode/Hacktoberfest2022#889]
I want to add program for no of islands in a matrix.

**Comment by AvTe** [comment]
Input : mat[][] = {{1, 1, 0, 0, 0},
                   {0, 1, 0, 0, 1},
                   {1, 0, 0, 1, 1},
                   {0, 0, 0, 0, 0},
                   {1, 0, 1, 0, 1}}
Output : 5

**Comment by blaze116** [comment]
hey @1dharode, kindly assign this issue to me

**Comment by surajkeshari** [comment]
Can you please assign this to me under Hacktoberfest label
i will add best question from leetcode.

**Comment by itsrishav17** [comment]
Hey, I want to work on this issue can you please assign it to me?
